authentication = [
  {
    mechanism = password_based
    backend = http
    method = post
    url = "http://nginx:3002/v1/internal/emqx/auth"
    headers {
      content_type = "application/json"
    }
    body {
      username = "${username}"
      password = "${password}"
      clientid = "${clientid}"
    }
    enable_pipelining = 1
    pool_size = 4
  }
]

authorization {
  no_match = allow
  sources = [
    {
      type = http
      enable = true
      method = post
      url = "http://nginx:3002/v1/internal/emqx/acl"
      headers {
        content_type = "application/json"
      }
      body {
        username = "${username}"
        topic = "${topic}"
        action = "${action}"
      }
      enable_pipelining = 1
      pool_size = 4
    }
  ]
}
