export declare const MCP_PROMPT_METADATA = "MCP_PROMPT_METADATA";
export declare const MCP_TOOL_METADATA = "MCP_TOOL_METADATA";
export declare const MCP_TOOL_WITH_PARAMS_METADATA = "MCP_TOOL_WITH_PARAMS_METADATA";
export declare const MCP_RESOURCE_METADATA = "MCP_RESOURCE_METADATA";
export declare const MCP_RESOURCE_TEMPLATE_METADATA = "MCP_RESOURCE_TEMPLATE_METADATA";
export declare const MCP_IS_PUBLIC = "MCP_IS_PUBLIC";
